# Generated by Django 2.2.3 on 2019-07-12 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('mobile_no', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('team', models.CharField(max_length=20)),
            ],
        ),
    ]
